name: Publish docs

on:
  repository_dispatch:
    types: [publish-doc]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Triggered by ${{ github.event.client_payload.source }}, version ${{ github.event.client_payload.version }}"

      - name: Checkout
        uses: actions/checkout@v1 # V1 does it by git clone, other versions do it by calling REST APIs.
        with:
          ref: 'pages'

      - name: Generate frontpage
        run: |
          echo "# kmod API Document" > README.md
          echo >> README.md
          ls -lr | awk '{print $1, $9}' | awk '/^d.* master/ {print "- ["$9"]("$9"/index.html)"}' >> README.md
          ls -lr | awk '{print $1, $9}' | awk '/^d.* v/ {print "- ["$2"]("$2"/index.html)"}' >> README.md

      - name: Commit and push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: 'github-actions[bot]'
          author_email: '41898282+github-actions[bot]@users.noreply.github.com'
          message: 'Auto-generating frontpage for ${{ github.event.client_payload.version }}'
          branch: 'pages'
          empty: true

      - name: Jekyll building
        uses: actions/jekyll-build-pages@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
